#!/usr/bin/env ruby

require "cartup"

COMMAND_RUN = "run"
COMMAND_INIT = "init"
COMMAND_HELP = "help"

command = ARGV[0]

commandHelper = CartBinaryUploader::CartupCommandHelper.new
commandHelper.handle command
